services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db # Utilise 'db' en local, remplacé par Railway en prod
      - DB_NAME=${DB_NAME:-cabinetmedical}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-Zinkrobin1}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-Zinkrobin1}
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME:-cabinetmedical}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-Zinkrobin1}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-Zinkrobin1}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER:-root}
      - PMA_PASSWORD=${DB_PASS:-Zinkrobin1}
      - PMA_PORT=3306
    restart: unless-stopped

volumes:
  mysql_data: